[package]
name = "zli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml = "0.3.0"
rpassword = "5.0.1"
clap = "3.1.0"
async-process = "1.3.0"
home = "0.5.3"
rusqlite = "0.27.0"